#Pré Processamento

In [ ]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler
from sklearn.cluster import KMeans
from sklearn import datasets
%matplotlib inline

In [ ]:
!unzip '/content/arquivo.zip'

Archive:  /content/arquivo.zip
  inflating: dataset-tortuga.csv     
  inflating: to_be_scored_tortuga.csv  


In [ ]:
#Importar biblioteca pandas
import pandas as pd
data = pd.read_csv('/content/dataset-tortuga.csv')

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 16 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   Unnamed: 0                        20000 non-null  int64  
 1   NAME                              20000 non-null  object 
 2   USER_ID                           20000 non-null  int64  
 3   HOURS_DATASCIENCE                 19986 non-null  float64
 4   HOURS_BACKEND                     19947 non-null  float64
 5   HOURS_FRONTEND                    19984 non-null  float64
 6   NUM_COURSES_BEGINNER_DATASCIENCE  19974 non-null  float64
 7   NUM_COURSES_BEGINNER_BACKEND      19982 non-null  float64
 8   NUM_COURSES_BEGINNER_FRONTEND     19961 non-null  float64
 9   NUM_COURSES_ADVANCED_DATASCIENCE  19998 non-null  float64
 10  NUM_COURSES_ADVANCED_BACKEND      19992 non-null  float64
 11  NUM_COURSES_ADVANCED_FRONTEND     19963 non-null  float64
 12  AVG_

In [ ]:
data.head()

Unnamed: 0               NAME   USER_ID  HOURS_DATASCIENCE  HOURS_BACKEND  \
0          28        Stormy Muto  58283940                7.0           39.0   
1          81       Carlos Ferro   1357218               32.0            0.0   
2          89  Robby Constantini  63212105               45.0            0.0   
3         138       Paul Mckenny  23239851               36.0           19.0   
4         143          Jean Webb  72234478               61.0           78.0   

   HOURS_FRONTEND  NUM_COURSES_BEGINNER_DATASCIENCE  \
0            29.0                               2.0   
1            44.0                               2.0   
2            59.0                               0.0   
3            28.0                               0.0   
4            38.0                               6.0   

   NUM_COURSES_BEGINNER_BACKEND  NUM_COURSES_BEGINNER_FRONTEND  \
0                           4.0                            0.0   
1                           0.0                            0.0   
2                           5.0                            4.0   
3                           5.0                            7.0   
4                          11.0                            0.0   

   NUM_COURSES_ADVANCED_DATASCIENCE  NUM_COURSES_ADVANCED_BACKEND  \
0                               2.0                           5.0   
1                               0.0                           5.0   
2                               0.0                           4.0   
3                               0.0                           5.0   
4                               4.0                           3.0   

   NUM_COURSES_ADVANCED_FRONTEND  AVG_SCORE_DATASCIENCE  AVG_SCORE_BACKEND  \
0                            0.0                   84.0               74.0   
1                            0.0                   67.0               45.0   
2                            1.0                    NaN               54.0   
3                            3.0                    NaN               71.0   
4                            0.0                   66.0               85.0   

   AVG_SCORE_FRONTEND                PROFILE  
0                 NaN     beginner_front_end  
1                 NaN     beginner_front_end  
2                47.0     advanced_front_end  
3                89.0  beginner_data_science  
4                 NaN     advanced_front_end

In [ ]:
#Removendo colunas que não serão relevantes para análise
#data_rc = Banco de dados com colunas removidas
data_rc = data.drop(columns=["Unnamed: 0", "NAME", "USER_ID"])

In [ ]:
data_rc.shape

(20000, 13)

In [ ]:
data_rc.head()

HOURS_DATASCIENCE  HOURS_BACKEND  HOURS_FRONTEND  \
0                7.0           39.0            29.0   
1               32.0            0.0            44.0   
2               45.0            0.0            59.0   
3               36.0           19.0            28.0   
4               61.0           78.0            38.0   

   NUM_COURSES_BEGINNER_DATASCIENCE  NUM_COURSES_BEGINNER_BACKEND  \
0                               2.0                           4.0   
1                               2.0                           0.0   
2                               0.0                           5.0   
3                               0.0                           5.0   
4                               6.0                          11.0   

   NUM_COURSES_BEGINNER_FRONTEND  NUM_COURSES_ADVANCED_DATASCIENCE  \
0                            0.0                               2.0   
1                            0.0                               0.0   
2                            4.0                               0.0   
3                            7.0                               0.0   
4                            0.0                               4.0   

   NUM_COURSES_ADVANCED_BACKEND  NUM_COURSES_ADVANCED_FRONTEND  \
0                           5.0                            0.0   
1                           5.0                            0.0   
2                           4.0                            1.0   
3                           5.0                            3.0   
4                           3.0                            0.0   

   AVG_SCORE_DATASCIENCE  AVG_SCORE_BACKEND  AVG_SCORE_FRONTEND  \
0                   84.0               74.0                 NaN   
1                   67.0               45.0                 NaN   
2                    NaN               54.0                47.0   
3                    NaN               71.0                89.0   
4                   66.0               85.0                 NaN   

                 PROFILE  
0     beginner_front_end  
1     beginner_front_end  
2     advanced_front_end  
3  beginner_data_science  
4     advanced_front_end

In [ ]:
#Verificar existencia de dados ausentes
data_rc.isnull().sum()

HOURS_DATASCIENCE                    14
HOURS_BACKEND                        53
HOURS_FRONTEND                       16
NUM_COURSES_BEGINNER_DATASCIENCE     26
NUM_COURSES_BEGINNER_BACKEND         18
NUM_COURSES_BEGINNER_FRONTEND        39
NUM_COURSES_ADVANCED_DATASCIENCE      2
NUM_COURSES_ADVANCED_BACKEND          8
NUM_COURSES_ADVANCED_FRONTEND        37
AVG_SCORE_DATASCIENCE               220
AVG_SCORE_BACKEND                    84
AVG_SCORE_FRONTEND                  168
PROFILE                               0
dtype: int64

In [ ]:
#Remoção de dados ausentes
#data_sa = Dataset sem dados ausentes
data_sa = data_rc.dropna()
data_sa.head()

HOURS_DATASCIENCE  HOURS_BACKEND  HOURS_FRONTEND  \
11               39.0           52.0            34.0   
12               28.0           44.0            16.0   
13               74.0           36.0            41.0   
14               69.0           40.0            18.0   
15               46.0          102.0            44.0   

    NUM_COURSES_BEGINNER_DATASCIENCE  NUM_COURSES_BEGINNER_BACKEND  \
11                               2.0                           4.0   
12                               3.0                           2.0   
13                               2.0                           5.0   
14                               4.0                           3.0   
15                               7.0                           9.0   

    NUM_COURSES_BEGINNER_FRONTEND  NUM_COURSES_ADVANCED_DATASCIENCE  \
11                            4.0                               1.0   
12                            5.0                               0.0   
13                            2.0                               3.0   
14                            5.0                               4.0   
15                            3.0                               5.0   

    NUM_COURSES_ADVANCED_BACKEND  NUM_COURSES_ADVANCED_FRONTEND  \
11                           5.0                            5.0   
12                           4.0                            4.0   
13                           4.0                            2.0   
14                           7.0                            6.0   
15                           3.0                            3.0   

    AVG_SCORE_DATASCIENCE  AVG_SCORE_BACKEND  AVG_SCORE_FRONTEND  \
11                   69.0               65.0                73.0   
12                   41.0               40.0                76.0   
13                   52.0               77.0                66.0   
14                   40.0               82.0                78.0   
15                   69.0               94.0                50.0   

                  PROFILE  
11       beginner_backend  
12  beginner_data_science  
13     advanced_front_end  
14  advanced_data_science  
15     advanced_front_end

In [ ]:
#Verificando o resultado da remoção de dados ausentes
data_sa.shape

(19328, 13)

In [ ]:
#Verificar se os dados ausentes foram removidos de todas os atributos
data_sa.isnull().sum()

HOURS_DATASCIENCE                   0
HOURS_BACKEND                       0
HOURS_FRONTEND                      0
NUM_COURSES_BEGINNER_DATASCIENCE    0
NUM_COURSES_BEGINNER_BACKEND        0
NUM_COURSES_BEGINNER_FRONTEND       0
NUM_COURSES_ADVANCED_DATASCIENCE    0
NUM_COURSES_ADVANCED_BACKEND        0
NUM_COURSES_ADVANCED_FRONTEND       0
AVG_SCORE_DATASCIENCE               0
AVG_SCORE_BACKEND                   0
AVG_SCORE_FRONTEND                  0
PROFILE                             0
dtype: int64

In [ ]:
data_sa.head()

HOURS_DATASCIENCE  HOURS_BACKEND  HOURS_FRONTEND  \
11               39.0           52.0            34.0   
12               28.0           44.0            16.0   
13               74.0           36.0            41.0   
14               69.0           40.0            18.0   
15               46.0          102.0            44.0   

    NUM_COURSES_BEGINNER_DATASCIENCE  NUM_COURSES_BEGINNER_BACKEND  \
11                               2.0                           4.0   
12                               3.0                           2.0   
13                               2.0                           5.0   
14                               4.0                           3.0   
15                               7.0                           9.0   

    NUM_COURSES_BEGINNER_FRONTEND  NUM_COURSES_ADVANCED_DATASCIENCE  \
11                            4.0                               1.0   
12                            5.0                               0.0   
13                            2.0                               3.0   
14                            5.0                               4.0   
15                            3.0                               5.0   

    NUM_COURSES_ADVANCED_BACKEND  NUM_COURSES_ADVANCED_FRONTEND  \
11                           5.0                            5.0   
12                           4.0                            4.0   
13                           4.0                            2.0   
14                           7.0                            6.0   
15                           3.0                            3.0   

    AVG_SCORE_DATASCIENCE  AVG_SCORE_BACKEND  AVG_SCORE_FRONTEND  \
11                   69.0               65.0                73.0   
12                   41.0               40.0                76.0   
13                   52.0               77.0                66.0   
14                   40.0               82.0                78.0   
15                   69.0               94.0                50.0   

                  PROFILE  
11       beginner_backend  
12  beginner_data_science  
13     advanced_front_end  
14  advanced_data_science  
15     advanced_front_end

In [ ]:
data_sa.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19328 entries, 11 to 19999
Data columns (total 13 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   HOURS_DATASCIENCE                 19328 non-null  float64
 1   HOURS_BACKEND                     19328 non-null  float64
 2   HOURS_FRONTEND                    19328 non-null  float64
 3   NUM_COURSES_BEGINNER_DATASCIENCE  19328 non-null  float64
 4   NUM_COURSES_BEGINNER_BACKEND      19328 non-null  float64
 5   NUM_COURSES_BEGINNER_FRONTEND     19328 non-null  float64
 6   NUM_COURSES_ADVANCED_DATASCIENCE  19328 non-null  float64
 7   NUM_COURSES_ADVANCED_BACKEND      19328 non-null  float64
 8   NUM_COURSES_ADVANCED_FRONTEND     19328 non-null  float64
 9   AVG_SCORE_DATASCIENCE             19328 non-null  float64
 10  AVG_SCORE_BACKEND                 19328 non-null  float64
 11  AVG_SCORE_FRONTEND                19328 non-null  float64
 12  PRO

In [ ]:
data_sa.describe()

HOURS_DATASCIENCE  HOURS_BACKEND  HOURS_FRONTEND  \
count       19328.000000   19328.000000    19328.000000   
mean           37.673013      43.571502       36.996120   
std            22.358256      22.326112       20.547631   
min             0.000000       0.000000        0.000000   
25%            21.000000      28.000000       22.000000   
50%            37.000000      43.000000       37.000000   
75%            53.000000      59.000000       51.000000   
max           127.000000     147.000000      124.000000   

       NUM_COURSES_BEGINNER_DATASCIENCE  NUM_COURSES_BEGINNER_BACKEND  \
count                      19328.000000                  19328.000000   
mean                           3.729046                      3.727183   
std                            1.983035                      2.092130   
min                            0.000000                      0.000000   
25%                            2.000000                      2.000000   
50%                            4.000000                      4.000000   
75%                            5.000000                      5.000000   
max                           12.000000                     12.000000   

       NUM_COURSES_BEGINNER_FRONTEND  NUM_COURSES_ADVANCED_DATASCIENCE  \
count                   19328.000000                      19328.000000   
mean                        4.073210                          3.421668   
std                         2.274433                          2.096466   
min                         0.000000                          0.000000   
25%                         2.000000                          2.000000   
50%                         4.000000                          3.000000   
75%                         6.000000                          5.000000   
max                        13.000000                         13.000000   

       NUM_COURSES_ADVANCED_BACKEND  NUM_COURSES_ADVANCED_FRONTEND  \
count                  19328.000000                   19328.000000   
mean                       4.345664                       3.396782   
std                        2.135325                       1.972702   
min                        0.000000                       0.000000   
25%                        3.000000                       2.000000   
50%                        4.000000                       3.000000   
75%                        6.000000                       5.000000   
max                       12.000000                      12.000000   

       AVG_SCORE_DATASCIENCE  AVG_SCORE_BACKEND  AVG_SCORE_FRONTEND  
count           19328.000000       19328.000000        19328.000000  
mean               65.014694          67.321916           67.200124  
std                13.935712          14.186334           14.369522  
min                 7.000000          10.000000            0.000000  
25%                56.000000          58.000000           58.000000  
50%                65.000000          68.000000           68.000000  
75%                75.000000          77.000000           77.000000  
max               100.000000         100.000000          100.000000

In [ ]:
data_sa.describe(include=['object'])

PROFILE
count              19328
unique                 6
top     advanced_backend
freq                3263

#KNN

In [ ]:
import scipy as scp
import warnings
warnings.filterwarnings('ignore')

In [ ]:

#Análise de distribuição dos dados da classe
from pandas._libs.tslibs.conversion import precision_from_unit
a = pd.value_counts(data_sa['PROFILE']) [0]
b = pd.value_counts(data_sa['PROFILE']) [1]
c = pd.value_counts(data_sa['PROFILE']) [2]
d = pd.value_counts(data_sa['PROFILE']) [3]
e = pd.value_counts(data_sa['PROFILE']) [4]
f = pd.value_counts(data_sa['PROFILE']) [5]

tam = len(data_sa)

print('Iniciantes Front-end: ', a)
print('Iniciantes Back-end: ', b)
print('Iniciantes DataScience: ', c)
print('Avançado Front-end: ', d)
print('Avançado Back-end: ', e)
print('Avançado DataScience: ', f)

pie = pd.DataFrame([['beginner_front_end', a],['beginner_backend', b],['beginner_data_science', c], 
                    ['advanced_front_end', d], ['advanced_backend', e], ['advanced_data_science', f]])

Iniciantes Front-end:  3263
Iniciantes Back-end:  3250
Iniciantes DataScience:  3244
Avançado Front-end:  3215
Avançado Back-end:  3209
Avançado DataScience:  3147


In [ ]:
# X =  colunas de informação, variáveis independentes
X = data_sa.drop('PROFILE', axis=1)
# y = Variável dependente, a qual será utilizada para classificar os dados
y = data_sa['PROFILE']

In [ ]:
X.head()

HOURS_DATASCIENCE  HOURS_BACKEND  HOURS_FRONTEND  \
11               39.0           52.0            34.0   
12               28.0           44.0            16.0   
13               74.0           36.0            41.0   
14               69.0           40.0            18.0   
15               46.0          102.0            44.0   

    NUM_COURSES_BEGINNER_DATASCIENCE  NUM_COURSES_BEGINNER_BACKEND  \
11                               2.0                           4.0   
12                               3.0                           2.0   
13                               2.0                           5.0   
14                               4.0                           3.0   
15                               7.0                           9.0   

    NUM_COURSES_BEGINNER_FRONTEND  NUM_COURSES_ADVANCED_DATASCIENCE  \
11                            4.0                               1.0   
12                            5.0                               0.0   
13                            2.0                               3.0   
14                            5.0                               4.0   
15                            3.0                               5.0   

    NUM_COURSES_ADVANCED_BACKEND  NUM_COURSES_ADVANCED_FRONTEND  \
11                           5.0                            5.0   
12                           4.0                            4.0   
13                           4.0                            2.0   
14                           7.0                            6.0   
15                           3.0                            3.0   

    AVG_SCORE_DATASCIENCE  AVG_SCORE_BACKEND  AVG_SCORE_FRONTEND  
11                   69.0               65.0                73.0  
12                   41.0               40.0                76.0  
13                   52.0               77.0                66.0  
14                   40.0               82.0                78.0  
15                   69.0               94.0                50.0

In [ ]:
#Importando o encoder para transformar as labels em chaves numéricas
from sklearn.preprocessing import OneHotEncoder
Oht_enc = OneHotEncoder()
X = pd.DataFrame(Oht_enc.fit_transform(X).A)

In [ ]:
X.shape

(19328, 713)

In [ ]:
#Dados de treinamento e teste
from sklearn.model_selection import train_test_split 
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.3)

In [ ]:
#Importando biblioteca
from sklearn.preprocessing import StandardScaler

In [ ]:
from sklearn.preprocessing import StandardScaler  
scaler = StandardScaler()  
scaler.fit(X_train)

X_train = scaler.transform(X_train)  
X_test = scaler.transform(X_test) 

In [ ]:
#Importando o modelo KNN
from sklearn.neighbors import KNeighborsClassifier  

# Definindo o valor de visinhos
classifier = KNeighborsClassifier(n_neighbors=6)  

#Treinando o modelo, com dados de treinamento
classifier.fit(X_train, y_train) 

KNeighborsClassifier(n_neighbors=6)

In [ ]:
#prever os resultados dos testes
y_pred = classifier.predict(X_test) 
y_pred

array(['beginner_data_science', 'advanced_data_science',
       'beginner_data_science', ..., 'advanced_backend',
       'beginner_front_end', 'advanced_data_science'], dtype=object)

In [ ]:
# Importando métricas para validação do modelo
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Imprimindo a matriz confusa
print("Matriz de confusão: ")
print(confusion_matrix(y_test, y_pred), "\n")  

# Imprimindo o relatório de classificação
print("Classificação: \n", classification_report(y_test, y_pred))  


# Imprimindo o quão acurado foi o modelo
print('Acurácia do modelo: ' , accuracy_score(y_test, y_pred))

Matriz Confusa: 
[[448 152 112 211  62  64]
 [210 388 103  89  48 104]
 [ 98 106 455  97 118  48]
 [191 141 155 360  86  59]
 [ 85 113 190 104 407  58]
 [101 156 123 151  86 320]] 

Relatório de classificação: 
                        precision    recall  f1-score   support

     advanced_backend       0.40      0.43      0.41      1049
advanced_data_science       0.37      0.41      0.39       942
   advanced_front_end       0.40      0.49      0.44       922
     beginner_backend       0.36      0.36      0.36       992
beginner_data_science       0.50      0.43      0.46       957
   beginner_front_end       0.49      0.34      0.40       937

             accuracy                           0.41      5799
            macro avg       0.42      0.41      0.41      5799
         weighted avg       0.42      0.41      0.41      5799

Acurácia do modelo:  0.4100707018451457


#Naive Bayes
https://colab.research.google.com/drive/1hwwEhYGezXg5cGtdcY7PXJFQndEwRSdG?usp=sharing

In [ ]:
#importando bibliotecas
import sklearn

In [ ]:
#conjunto de dados
X = data_sa.iloc[:, [1, 2, 3]].values
y = data_sa.iloc[:, -1].values

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,0] = le.fit_transform(X[:,0])

In [ ]:
#definindo conjunto de treinamento e teste
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
#treinamento do modelo
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [ ]:
#prever resultados dos testes
y_pred  =  classifier.predict(X_test)

In [ ]:
#avalição usando matriz de confusão e acurácia
from sklearn.metrics import confusion_matrix,accuracy_score
matriz = confusion_matrix(y_test, y_pred)
acuracia = accuracy_score(y_test,y_pred)

In [ ]:
matriz

array([[285,  95, 106,  59,  12,  79],
       [276, 124, 102,  48,  69,  68],
       [ 43,  24, 291,  48, 166,  69],
       [ 85,  56,  90, 173,  98, 129],
       [ 31,  23, 109,  12, 304, 142],
       [ 80,  25,  43,  79, 119, 304]])

In [ ]:
acuracia

0.38308329022245213

In [ ]:
from sklearn.metrics import classification_report
# Imprimindo o relatório de classificação
print("Classificação: \n", classification_report(y_test, y_pred))  

Relatório de classificação: 
                        precision    recall  f1-score   support

     advanced_backend       0.36      0.45      0.40       636
advanced_data_science       0.36      0.18      0.24       687
   advanced_front_end       0.39      0.45      0.42       641
     beginner_backend       0.41      0.27      0.33       631
beginner_data_science       0.40      0.49      0.44       621
   beginner_front_end       0.38      0.47      0.42       650

             accuracy                           0.38      3866
            macro avg       0.38      0.39      0.37      3866
         weighted avg       0.38      0.38      0.37      3866

